apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fcg-tutorial

resources:
  - namespace.yaml
  - sqlserver.yaml
  - fcg-fixed.yaml
  - games.yaml
  - payments.yaml

images:
  - name: fcg-presentation:local
    newName: dtpontes/fcgpresentation
    newTag: latest
  - name: games-presentation:local
    newName: dtpontes/fcggamespresentation
    newTag: latest
  - name: payments-presentation:local
    newName: dtpontes/fcgpaymentspresentation
    newTag: latest
